id: I28104BB0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T23:22:37+00:00'
last_modified: '2022-06-08T10:55:10.593257+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30379
  title: ལམ་རིམ་ལེགས་གསུང་ཀུན་གྱི་ཉིང་ཁུ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    8AD9:
      image_group_id: I1KG21283
      title: ''
      total_pages: 172
      order: 1
      base_file: 8AD9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
