id: P009421
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W30379
  title: ལམ་རིམ་ལེགས་གསུང་ཀུན་གྱི་ཉིང་ཁུ།
  author: ''
  volumes:
    52e1b237d4e54f66a51a6a93ff80d85c:
      image_group_id: I1KG21283
      title: ''
      volume_number: 1
      total_pages: 172
      base_file: v001.txt
